// <auto-generated />
using System;
using LuxuryRental.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyDotNetApp.ApiService.Migrations
{
    [DbContext(typeof(RentalContext))]
    [Migration("20251028203215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LuxuryRental.Api.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = "Supercar",
                            ImageUrl = "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&h=600&fit=crop",
                            IsAvailable = true,
                            Make = "Ferrari",
                            Model = "Roma",
                            PricePerDay = 1200m
                        },
                        new
                        {
                            Id = 2,
                            Class = "Supercar",
                            ImageUrl = "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&h=600&fit=crop",
                            IsAvailable = true,
                            Make = "Lamborghini",
                            Model = "Huracán",
                            PricePerDay = 1500m
                        },
                        new
                        {
                            Id = 3,
                            Class = "Sports",
                            ImageUrl = "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=600&fit=crop",
                            IsAvailable = true,
                            Make = "Porsche",
                            Model = "911 Turbo S",
                            PricePerDay = 900m
                        },
                        new
                        {
                            Id = 4,
                            Class = "Supercar",
                            ImageUrl = "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&h=600&fit=crop",
                            IsAvailable = true,
                            Make = "McLaren",
                            Model = "720S",
                            PricePerDay = 1300m
                        },
                        new
                        {
                            Id = 5,
                            Class = "Luxury",
                            ImageUrl = "https://images.unsplash.com/photo-15493995427e3f8b79c341?w=800&h=600&fit=crop",
                            IsAvailable = true,
                            Make = "Bentley",
                            Model = "Continental GT",
                            PricePerDay = 800m
                        },
                        new
                        {
                            Id = 6,
                            Class = "Grand Tourer",
                            ImageUrl = "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop",
                            IsAvailable = true,
                            Make = "Aston Martin",
                            Model = "DB11",
                            PricePerDay = 1100m
                        },
                        new
                        {
                            Id = 7,
                            Class = "Ultra Luxury",
                            ImageUrl = "https://images.unsplash.com/photo-1563720360172-67b8f3dce741?w=800&h=600&fit=crop",
                            IsAvailable = true,
                            Make = "Rolls-Royce",
                            Model = "Wraith",
                            PricePerDay = 1800m
                        },
                        new
                        {
                            Id = 8,
                            Class = "Sports",
                            ImageUrl = "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=600&fit=crop",
                            IsAvailable = true,
                            Make = "Mercedes-AMG",
                            Model = "GT R",
                            PricePerDay = 950m
                        });
                });

            modelBuilder.Entity("LuxuryRental.Api.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int?>("CarId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("RenterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CarId1");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("LuxuryRental.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LuxuryRental.Api.Models.Rental", b =>
                {
                    b.HasOne("LuxuryRental.Api.Models.Car", null)
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuxuryRental.Api.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId1");

                    b.HasOne("LuxuryRental.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuxuryRental.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("Car");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
