// <auto-generated />
using System;
using LuxuryRental.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyDotNetApp.ApiService.Migrations
{
    [DbContext(typeof(RentalContext))]
    partial class RentalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LuxuryRental.Api.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = "Supercar",
                            ImageUrl = "https://cdn.dicklovett.co.uk/uploads/used_stock_image/1_2507021_e.jpg?v=1758203924",
                            IsAvailable = true,
                            Make = "Ferrari",
                            Model = "Roma",
                            PricePerDay = 1200m
                        },
                        new
                        {
                            Id = 2,
                            Class = "Supercar",
                            ImageUrl = "https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/huracan/evo/connected_car/hura_connect_over_03_m.jpg",
                            IsAvailable = true,
                            Make = "Lamborghini",
                            Model = "Huracán EVO",
                            PricePerDay = 1500m
                        },
                        new
                        {
                            Id = 3,
                            Class = "Supercar",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKg_qn5PLG9GS20nutnZqVVue14ZlkSo2-oQ&s",
                            IsAvailable = true,
                            Make = "McLaren",
                            Model = "720S",
                            PricePerDay = 1300m
                        },
                        new
                        {
                            Id = 4,
                            Class = "Sports",
                            ImageUrl = "https://www.kbb.com/wp-content/uploads/2020/04/2021-porsche-911-turbo-s-coupe-front.jpg",
                            IsAvailable = true,
                            Make = "Porsche",
                            Model = "911 Turbo S",
                            PricePerDay = 950m
                        },
                        new
                        {
                            Id = 5,
                            Class = "Grand Tourer",
                            ImageUrl = "https://images.caricos.com/a/aston_martin/2017_aston_martin_db11_lightning_silver/images/2560x1440/2017_aston_martin_db11_lightning_silver_130_2560x1440.jpg",
                            IsAvailable = true,
                            Make = "Aston Martin",
                            Model = "DB11",
                            PricePerDay = 1100m
                        },
                        new
                        {
                            Id = 6,
                            Class = "Luxury",
                            ImageUrl = "https://www.bentleymotors.com/content/dam/bm/websites/bmcom/bentleymotors-com/models/25my/25my-gt/Gallery%202.jpg/_jcr_content/renditions/original.image_file.1440.810.file/Gallery%202.jpg",
                            IsAvailable = true,
                            Make = "Bentley",
                            Model = "Continental GT",
                            PricePerDay = 850m
                        },
                        new
                        {
                            Id = 7,
                            Class = "Ultra Luxury",
                            ImageUrl = "https://editorial.pxcrush.net/carsales/general/editorial/rolls-royce-wraith-black-arrow-exterior-06.jpg?height=682&width=1024",
                            IsAvailable = true,
                            Make = "Rolls-Royce",
                            Model = "Wraith",
                            PricePerDay = 1800m
                        },
                        new
                        {
                            Id = 8,
                            Class = "Hypercar",
                            ImageUrl = "https://fortune.com/img-assets/wp-content/uploads/2016/02/01_chiron_front_web.jpg",
                            IsAvailable = true,
                            Make = "Bugatti",
                            Model = "Chiron",
                            PricePerDay = 3500m
                        },
                        new
                        {
                            Id = 9,
                            Class = "Luxury Sedan",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvgP7ERASZM6mX5tulnpIkSJkyir4LUJd7uA&s",
                            IsAvailable = true,
                            Make = "Mercedes‑Benz",
                            Model = "S‑Class",
                            PricePerDay = 600m
                        },
                        new
                        {
                            Id = 10,
                            Class = "Luxury Sedan",
                            ImageUrl = "https://first-gt.com/wp-content/uploads/2021/05/bmw-7-series.jpg",
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "7 Series",
                            PricePerDay = 580m
                        },
                        new
                        {
                            Id = 11,
                            Class = "Luxury Sedan",
                            ImageUrl = "https://www.latribuneauto.com/media/cache/resolve/vehicule_slider/photos/AUDI/A8/AUDI-A8-BE-22-119947/01%20Audi%20A8%202022%20Exterieur%203%204%20Avant.jpg",
                            IsAvailable = true,
                            Make = "Audi",
                            Model = "A8",
                            PricePerDay = 550m
                        },
                        new
                        {
                            Id = 12,
                            Class = "Luxury Sedan",
                            ImageUrl = "https://hips.hearstapps.com/hmg-prod/images/2025-lexus-ls-500-f-sport-awd-101-67e30ab19aa60.jpg?crop=0.635xw:0.476xh;0.274xw,0.404xh&resize=1200:*",
                            IsAvailable = true,
                            Make = "Lexus",
                            Model = "LS 500",
                            PricePerDay = 500m
                        },
                        new
                        {
                            Id = 13,
                            Class = "Electric",
                            ImageUrl = "https://octane.rent/wp-content/uploads/2024/11/tesla_model_s_black_01.jpg",
                            IsAvailable = true,
                            Make = "Tesla",
                            Model = "Model S Plaid",
                            PricePerDay = 400m
                        },
                        new
                        {
                            Id = 14,
                            Class = "Electric",
                            ImageUrl = "https://lucidmotors.com/s3fs-public/2022-10/slideshow-00-regular.webp",
                            IsAvailable = true,
                            Make = "Lucid",
                            Model = "Air Dream Edition",
                            PricePerDay = 420m
                        },
                        new
                        {
                            Id = 15,
                            Class = "Electric Sports",
                            ImageUrl = "https://cms-assets.autoscout24.com/uaddx06iwzdz/4ShcqL35AjjiQepEF2N6Y3/21f6bd40209e3016673b970d9143464d/porsche_taycan_732.jpeg?w=1100",
                            IsAvailable = true,
                            Make = "Porsche",
                            Model = "Taycan Turbo S",
                            PricePerDay = 480m
                        },
                        new
                        {
                            Id = 16,
                            Class = "Electric Luxury",
                            ImageUrl = "https://mediacloud.carbuyer.co.uk/image/private/s--X-WVjvBW--/f_auto,t_content-image-full-desktop@1/v1723215907/autoexpress/2024/08/BMW%20i7%20eDrive50%20M%20Sport%202024%20UK-22.jpg",
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "i7",
                            PricePerDay = 450m
                        },
                        new
                        {
                            Id = 17,
                            Class = "Electric",
                            ImageUrl = "https://c0.lestechnophiles.com/www.numerama.com/wp-content/uploads/2025/08/essai-tesla-model-3-performance-2025-12.jpg?resize=1600,900&key=190b7a19&watermark",
                            IsAvailable = true,
                            Make = "Tesla",
                            Model = "Model 3 Performance",
                            PricePerDay = 250m
                        },
                        new
                        {
                            Id = 18,
                            Class = "SUV",
                            ImageUrl = "https://www.dealndrive.com/Content/images/upload/28669-full.jpg",
                            IsAvailable = true,
                            Make = "Range Rover",
                            Model = "Sport",
                            PricePerDay = 550m
                        },
                        new
                        {
                            Id = 19,
                            Class = "SUV",
                            ImageUrl = "https://autobunny-docs.s3.ca-central-1.amazonaws.com/945/car/forsale/images/2024/02/pic-b470b1283d251a143bc46acd4f1036a5.jpg",
                            IsAvailable = true,
                            Make = "Mercedes‑Benz",
                            Model = "GLE",
                            PricePerDay = 400m
                        },
                        new
                        {
                            Id = 20,
                            Class = "SUV",
                            ImageUrl = "https://bmw.scene7.com/is/image/BMW/bmw-x-series-overview-x5-g05?wid=2560&hei=2560",
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "X5",
                            PricePerDay = 380m
                        },
                        new
                        {
                            Id = 21,
                            Class = "SUV",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkmYnqx2o6zA7CCuyzBrdkyFkwxcAA7RDAbQ&s",
                            IsAvailable = true,
                            Make = "Audi",
                            Model = "Q8",
                            PricePerDay = 420m
                        },
                        new
                        {
                            Id = 22,
                            Class = "Super SUV",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU_8P8oHyUfeGjls8ax7mRIlZGEufIyQQCvg&s",
                            IsAvailable = true,
                            Make = "Lamborghini",
                            Model = "Urus",
                            PricePerDay = 1200m
                        },
                        new
                        {
                            Id = 23,
                            Class = "Luxury SUV",
                            ImageUrl = "https://www.bentleymedia.com/image/dda38b10-c8f6-41b6-af44-e17e820ced39?anchor=middlecenter&bgcolor=Transparent&borderWidth=0&crop=0%2C0%2C0%2C0&width=460",
                            IsAvailable = true,
                            Make = "Bentley",
                            Model = "Bentayga",
                            PricePerDay = 950m
                        },
                        new
                        {
                            Id = 24,
                            Class = "SUV",
                            ImageUrl = "https://www.turbo.fr/sites/default/files/2019-09/maserati-levante-trofeo-essai.png",
                            IsAvailable = true,
                            Make = "Maserati",
                            Model = "Levante",
                            PricePerDay = 600m
                        },
                        new
                        {
                            Id = 45,
                            Class = "Luxury 4x4",
                            ImageUrl = "https://ik.imagekit.io/vyro/public/autofox-api-mapped-to-vehicles/b81f83f332e9a3fce6d255c0f45f2103033e7f706068f23d967c85d99b593635.jpg",
                            IsAvailable = true,
                            Make = "Mercedes-Benz",
                            Model = "G-Class",
                            PricePerDay = 950m
                        },
                        new
                        {
                            Id = 51,
                            Class = "Supercar",
                            ImageUrl = "https://cdn.ferrari.com/cms/network/media/img/resize/5d26fdb7c3f9ec0af6475619-01_fb_ppl_intro_lp3lhwq8?width=1080",
                            IsAvailable = true,
                            Make = "Ferrari",
                            Model = "F8 Tributo",
                            PricePerDay = 1400m
                        },
                        new
                        {
                            Id = 52,
                            Class = "Supercar",
                            ImageUrl = "https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/aventador/s/s/s-3_M.jpg",
                            IsAvailable = true,
                            Make = "Lamborghini",
                            Model = "Aventador",
                            PricePerDay = 2000m
                        },
                        new
                        {
                            Id = 54,
                            Class = "Sports",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/3/32/Porsche_718_Cayman_%28MSP17%29.jpg",
                            IsAvailable = true,
                            Make = "Porsche",
                            Model = "718 Cayman GT4",
                            PricePerDay = 900m
                        },
                        new
                        {
                            Id = 55,
                            Class = "Sports",
                            ImageUrl = "https://www.largus.fr/images/styles/max_1300x1300/public/2024-02/aston-martin-vantage-2024-jaune-avg-mk.jpg?itok=EhIDUYJs",
                            IsAvailable = true,
                            Make = "Aston Martin",
                            Model = "Vantage",
                            PricePerDay = 1100m
                        },
                        new
                        {
                            Id = 56,
                            Class = "Electric SUV",
                            ImageUrl = "https://images.caradisiac.com/logos/2/0/2/6/272026/S8-essai-tesla-model-y-performance-2022-on-en-a-pour-son-argent-196566.jpg",
                            IsAvailable = true,
                            Make = "Tesla",
                            Model = "Model Y Performance",
                            PricePerDay = 350m
                        },
                        new
                        {
                            Id = 57,
                            Class = "Electric SUV",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNn-A9iJfxvdmAV4gdDmORCazOtdvVadTxfw&s",
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "iX",
                            PricePerDay = 400m
                        },
                        new
                        {
                            Id = 58,
                            Class = "Electric Sports",
                            ImageUrl = "https://www.automobile-magazine.fr/asset/cms/1200x750/226448/config/173544/audi-rs-e-tron-gt-av.jpg",
                            IsAvailable = true,
                            Make = "Audi",
                            Model = "e-tron GT",
                            PricePerDay = 450m
                        },
                        new
                        {
                            Id = 59,
                            Class = "Electric Sports",
                            ImageUrl = "https://www.hoonited.com/wp-content/uploads/2024/12/Porsche-Taycan-4S-2024-15.jpg",
                            IsAvailable = true,
                            Make = "Porsche",
                            Model = "Taycan 4S",
                            PricePerDay = 420m
                        },
                        new
                        {
                            Id = 61,
                            Class = "SUV",
                            ImageUrl = "https://hips.hearstapps.com/hmg-prod/images/2020-audi-q7-134-1583273378.jpg?crop=0.891xw:0.751xh;0.0782xw,0.249xh&resize=2048:*",
                            IsAvailable = true,
                            Make = "Audi",
                            Model = "Q7",
                            PricePerDay = 400m
                        },
                        new
                        {
                            Id = 62,
                            Class = "SUV",
                            ImageUrl = "https://www.largus.fr/images/styles/max_1300x1300/public/images/bmw-x6-2019-vue-av.jpg?itok=QvwSVz1Z",
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "X6",
                            PricePerDay = 450m
                        },
                        new
                        {
                            Id = 63,
                            Class = "Luxury SUV",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Mercedes-Benz_X_167_GLS580_IAA_2019_JM_0265.jpg/330px-Mercedes-Benz_X_167_GLS580_IAA_2019_JM_0265.jpg",
                            IsAvailable = true,
                            Make = "Mercedes-Benz",
                            Model = "GLS",
                            PricePerDay = 550m
                        },
                        new
                        {
                            Id = 64,
                            Class = "SUV",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/8/88/Range_Rover_Velar.jpg",
                            IsAvailable = true,
                            Make = "Range Rover",
                            Model = "Velar",
                            PricePerDay = 480m
                        },
                        new
                        {
                            Id = 65,
                            Class = "Luxury SUV",
                            ImageUrl = "https://www.largus.fr/images/styles/max_1300x1300/public/images/maserati-levante-trofeo-24.jpg?itok=Lr0Hjp4N",
                            IsAvailable = true,
                            Make = "Maserati",
                            Model = "Levante Trofeo",
                            PricePerDay = 600m
                        },
                        new
                        {
                            Id = 66,
                            Class = "Luxury Sedan",
                            ImageUrl = "https://www.mbusa.com/content/dam/mb-nafta/us/myco/my26/e-class/e-sedan/class-page/2026-E-SEDAN-HC-D.jpg",
                            IsAvailable = true,
                            Make = "Mercedes-Benz",
                            Model = "E-Class",
                            PricePerDay = 350m
                        },
                        new
                        {
                            Id = 67,
                            Class = "Luxury Sedan",
                            ImageUrl = "https://cdn.motor1.com/images/mgl/KrpgM/s3/2017-bmw-5-series.jpg",
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "5 Series",
                            PricePerDay = 340m
                        },
                        new
                        {
                            Id = 68,
                            Class = "Luxury Sedan",
                            ImageUrl = "https://images.ctfassets.net/uaddx06iwzdz/7aPSWTuHLGAcn6ps5BniGs/aa11e9bf7f6d7d89365f4481522eaa89/audi-a6-front.jpg",
                            IsAvailable = true,
                            Make = "Audi",
                            Model = "A6",
                            PricePerDay = 330m
                        });
                });

            modelBuilder.Entity("LuxuryRental.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RelatedRentalId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RelatedRentalId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LuxuryRental.Api.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("RenterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("LuxuryRental.Api.Models.RentalDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileContent")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RentalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RentalId");

                    b.ToTable("RentalDocuments");
                });

            modelBuilder.Entity("LuxuryRental.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LuxuryRental.Api.Models.Notification", b =>
                {
                    b.HasOne("LuxuryRental.Api.Models.Rental", "RelatedRental")
                        .WithMany()
                        .HasForeignKey("RelatedRentalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LuxuryRental.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedRental");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxuryRental.Api.Models.Rental", b =>
                {
                    b.HasOne("LuxuryRental.Api.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuxuryRental.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxuryRental.Api.Models.RentalDocument", b =>
                {
                    b.HasOne("LuxuryRental.Api.Models.Rental", "Rental")
                        .WithMany()
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rental");
                });
#pragma warning restore 612, 618
        }
    }
}
